# 数据库配置
spring:
    application:
        name: chatroom
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/chatroom?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&useUnicode=true&allowPublicKeyRetrieval=true
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: 123456
        # Druid 连接池配置
        druid:
            initial-size: 5
            min-idle: 5
            max-active: 20
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            # SQL 日志配置
            stat-sql-enable: true
            log-slow-sql: true
            slow-sql-millis: 1000

    redis:
        database: 0 # 数据库编号（默认为0）
        host: localhost # Redis服务器地址
        port: 6379 # Redis服务器端口
        #password:  # Redis密码（如果设置了密码）
        timeout: 3000ms # 连接超时时间（可选）
        jedis:
            pool:
                max-active: 8 # 最大活动连接数
                max-idle: 8 # 最大空闲连接数
                min-idle: 0 # 最小空闲连接数
                max-wait: -1ms # 等待可用连接的最大时间（负值表示无限等待）

redisson:
    config:
    single-server-config:
        address: "redis://127.0.0.1:6379"
        # password: "your_password" # 如果没有密码，这一行可以省略
        connection-pool-size: 50
        connection-minimum-idle-size: 10

#sql日志显示
#mybatis:
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    #mapper文件位置配置
#        mapper-locations: classpath:mapper/*.xml

#端口号配置
server:
    port: 8082

    #FastDFS文件服务器的主机名
fastdfs:
    nginx:
        host:

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL日志
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto # 主键策略
      field-strategy: not_empty
      table-underline: true
      logic-delete-field: isDeleted # 逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/*.xml


